Add home work 2
panok90/JS pull request #2
Opened 2021-07-12 14:36 UTC by panok90

2021-07-12 15:20 UTC, panok90 reviewed
Variables changed

2021-07-13 16:01 UTC, Om1X requested changes

2021-07-13 16:01 UTC, Om1X commented on HomeWork-2/script.js
> +            return 'Попробуйте еще раз! :(';
Результат не консистентен. Я ожидаю именно число, а не строку с пояснением.

2021-07-14 21:52 UTC, Om1X approved these changes

2021-07-19 14:04 UTC, merged